### ISSUE TITLE
Downloader UI empty template

### ISSUE THREAD

**Issue by michalpustelnik7209** [TheBobPony/BPDownloadsGUI#6]
@TheBobPony 
I want an Downloader UI empty template with options:
Select version
Select language
Select file.
I want JSON generator that allows me to make list of files and make text script for me.
E.g.
Version: 1.0, Language: English, File: example.zip
Thanks!

**Comment by omaemae** [comment]
what

**Comment by michalpustelnik7209** [comment]
I want a empty template of Downloader UI that is on Bobpony website

**Comment by omaemae** [comment]
> I want a empty template of Downloader UI that is on Bobpony website

we won't make it for you, neither will Bob

you're free to fork this and do whatever

**Comment by michalpustelnik7209** [comment]
fine
